// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// Thinger is an autogenerated mock type for the Thinger type
type Thinger struct {
	mock.Mock
}

// Thing provides a mock function with given fields: val
func (_m *Thinger) Thing(val string) string {
	ret := _m.Called(val)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
